/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'stm32l072-base.Release+STM32L072RB' 
 * Target:  'Release+STM32L072RB' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
        #define CMSIS_device_header "stm32l0xx.h"


#endif /* RTE_COMPONENTS_H */
